M48
; DRILL file {KiCad 9.0.0} date 2025-04-07T20:51:01+0530
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2025-04-07T20:51:01+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X106150Y-75655
X107650Y-39655
X183650Y-39655
X185150Y-75655
M30
